
def main ():
  return "Hello, World!"
# Ok agora para rodar o Bend é preciso escrever bend run e o nome do arquivo que eu quero que rode, nesse caso para rodar o "Hello World!" vai ser preciso escrever: bend run aprendendo.bend

# def am_i_old (age):
#   if age < 18 :
#     return "you are a kid"
#   else:
#     return "you are an adult"  
  
# def main ():
#   return am_i_old ()

# Sempre só pode ter uma função main e sempre é bom deixar ela no final do código/por última.  